name: Deploy to Glitch

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Fetch the full history to avoid shallow push issues

      - name: Pull from GitHub to Glitch
        run: |
          git remote add glitch https://47bf7aca-d088-46de-bde7-e52b768eb8d9@api.glitch.com/git/pebble-romantic-substance
          git fetch origin
          git reset --hard origin/main
          git pull origin main
